FROM python:3.11

WORKDIR /code

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Run your FastAPI app (which wraps your Flask app)
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]